name: Push commit
on: push
jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Format code
        run: ./node_modules/.bin/prettier solutions/*.js -w
      - name: Update badge
        run: node update-badge.js
      - name: Commit badge
        run: |
          git config --global user.name 'AutoBot'
          git config --global user.email 'AutoBot@users.noreply.github.com'
          git commit -am "Automated badge update."
          git push
